nome = 'Matheus'
print(nome[0])
print(nome[1])
print(len(nome))
print(len(nome) - 1)
print(nome[-1])
print(nome[-2])
print(nome[0:3])
print(nome[1:3])
print(nome[-3:])
print(nome[3:])
print(nome[:4:2])
print(nome[::-1])
lista = list(range(10))
print(lista[0])
print(lista[-1])
print(lista[:3])
print(lista[::-1])
print(len(lista))


